DROP TABLE IF EXISTS OTA_FORBOARD;
DROP TABLE IF EXISTS OTA_RELEASES;
DROP TABLE IF EXISTS OTA_ACCESS;

CREATE TABLE OTA_ACCESS (
  TIMEST TIMESTAMP,
  USER_AGENT CHAR(50),
  CHIP_ID CHAR(15),
  STA_MAC CHAR(17),
  AP_MAC CHAR(17),
  FREE_SPACE DECIMAL(10,0),
  SKETCH_SIZE DECIMAL(10,0),
  SKETCH_MD5 CHAR(40),
  CHIP_SIZE DECIMAL(10,0),
  SDK_VERSION CHAR(40),
  FW_MODE CHAR(20),
  VERSION CHAR(15) COMMENT '6 major cioè nome del fw, 9 minor',
  PRIMARY KEY(TIMEST, STA_MAC)
);

CREATE TABLE OTA_RELEASES (
  SWID CHAR(6) COMMENT '6 major',
  SWVERS CHAR(9) COMMENT '9 del minor',
  RELEASED TIMESTAMP,
  EXPIRES TIMESTAMP NOT NULL,
  DISABLED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (SWID, SWVERS, RELEASED)
);

CREATE TABLE OTA_FORBOARD (
  STA_MAC CHAR(17),
  SWID CHAR(6),
  SWVERS CHAR(9),
  RELEASED TIMESTAMP,
  PRIMARY KEY (STA_MAC, SWID, SWVERS, RELEASED),
  FOREIGN KEY (SWID, SWVERS, RELEASED) 
    REFERENCES OTA_RELEASES(SWID, SWVERS, RELEASED)
);
