DROP TABLE IF EXISTS OTA_FORBOARD;
DROP TABLE IF EXISTS OTA_RELEASES;
DROP TABLE IF EXISTS OTA_ACCESS;

CREATE TABLE OTA_ACCESS (
  TIMEST TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USER_AGENT CHAR(50),
  CHIP_ID CHAR(15),
  STA_MAC CHAR(17),
  AP_MAC CHAR(17),
  FREE_SPACE DECIMAL(10,0),
  SKETCH_SIZE DECIMAL(10,0),
  SKETCH_MD5 CHAR(40),
  CHIP_SIZE DECIMAL(10,0),
  SDK_VERSION CHAR(40),
  FW_MODE CHAR(20),
  VERSION CHAR(15)
     COMMENT '6 x firmware name, _ (separator), 8 x firmware version',
  PRIMARY KEY(TIMEST, STA_MAC)
)
  COMMENT 'LOG OF CHECKS'
;

CREATE TABLE OTA_RELEASES (
  SWID CHAR(6) COMMENT 'firmware name',
  SWVERS CHAR(8) COMMENT 'firmware version',
  RELEASED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRES TIMESTAMP NOT NULL DEFAULT '2038-01-01 00:00:00'
     COMMENT 'DATE AFTER WHICH IT IS NOT DOWNLOADABLE',
  ENABLED BOOLEAN NOT NULL DEFAULT FALSE
     COMMENT 'IF FALSE, IT IS NOT DOWNLOADABLE',
  MACRESTRICTED BOOLEAN NOT NULL DEFAULT FALSE
     COMMENT 'IF TRUE, RESERVED FOR SPECIFIC MACs',
  PRIMARY KEY (SWID, SWVERS)
)
  COMMENT 'FIRMWARE RELEASES, ONLY THE NEWER AVAILABLE IS SENT'
;

CREATE TABLE OTA_FORBOARD (
  STA_MAC CHAR(17),
  SWID CHAR(6),
  SWVERS CHAR(8),
  ENABLED BOOLEAN NOT NULL DEFAULT FALSE
     COMMENT 'IF FALSE, IT IS NOT APPLICABLE',
  PRIMARY KEY (STA_MAC, SWID, SWVERS),
  FOREIGN KEY (SWID, SWVERS) 
    REFERENCES OTA_RELEASES(SWID, SWVERS)
)
  COMMENT 'FOR SPECIFIC BOARD UPDATES, IDENTIFIED BY MAC ADDR'
;
